Quieter backup; also log autoupdate output.

diff --git a/packages/buendia-backup/data/usr/bin/buendia-backup b/packages/buendia-backup/data/usr/bin/buendia-backup
--- a/packages/buendia-backup/data/usr/bin/buendia-backup
+++ b/packages/buendia-backup/data/usr/bin/buendia-backup
@@ -40,14 +40,22 @@ mkdir -p $deb_dir
 
 # ---- Back up MySQL data
 
-buendia-mysql-dump openmrs $dir/openmrs.zip
+echo "Dumping MySQL database..."
+tmp=/tmp/buendia-mysql-dump.$$
+trap 'rm -f $tmp' EXIT
+if ! buendia-mysql-dump openmrs $dir/openmrs.zip >$tmp 2>&1; then
+    cat $tmp
+    echo "buendia-mysql-dump failed!"
+    exit 1
+fi
+ls -l $dir/openmrs.zip
 
 # ---- Back up the package list and non-base packages
 
 # Examine what packages are installed.
 dpkg-query -W --showformat '${Package}=${Version}\n' | sort > $dir/all.list
 comm -2 -3 $dir/all.list /etc/base.packages.list | sort > $dir/buendia.list
-echo Backing up $(cat $dir/buendia.list | wc -l) packages.
+echo Backing up $(cat $dir/buendia.list | wc -l) packages...
 
 for package in $(cat $dir/buendia.list); do
     package=$(echo $package | tr = _ | sed -e 's/:/%3a/g')
