Fix missing dependency on buendia-status.

diff --git a/packages/buendia-monitoring/data/usr/bin/buendia-log b/packages/buendia-monitoring/data/usr/bin/buendia-log
--- a/packages/buendia-monitoring/data/usr/bin/buendia-log
+++ b/packages/buendia-monitoring/data/usr/bin/buendia-log
@@ -1,60 +1,49 @@
-#!/bin/bash
-
-set -e; . /usr/share/buendia/utils.sh
-
-if [ "$1" = "" -o "$1" = "-h" ]; then
-    echo "Usage: $0 [-y] <command>"
-    echo
-    echo "Runs a command and logs its output under /var/log/buendia, exiting"
-    echo "with the exit status of the command.  Specify -y to run the command"
-    echo "in Yocto; otherwise it will run in Debian."
-    exit 1
-fi
-
-if [ "$1" = "-y" ]; then
-    yocto=yes
-    shift
-fi
-
-# Name the log file after the first word in the command.
-logfile=/var/log/buendia/$(basename $(echo "$*" | sed -e 's/ .*//')).log
-mkdir -p /var/log/buendia
-
-tmp=/tmp/buendia-log.$$
-rm -rf $tmp
-mkdir -p $tmp
-trap 'rm -rf $tmp' EXIT
-
-# This is the pid of this logging script rather than the pid of the command,
-# but it still helps to distinguish this run from other concurrent runs.
-export LOGGER_PID=$$
-
-unindent <<< '
-    #!/usr/bin/perl -n
-
-    $| = 1;  # unbuffer output
-    my ($s, $m, $h, $d, $l, $y) = gmtime();
-    printf "%04d-%02d-%02d %02d:%02d:%02d %5d> ",
-        $y + 1900, $l + 1, $d, $h, $m, $s, $ENV{"LOGGER_PID"};
-    s/^\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d //;
-    print $_;
-' | create $tmp/add_timestamps
-chmod 755 $tmp/add_timestamps
-
-# Save the exit status of the command so we can exit with the same status.
-export RESULT_FILE=$tmp/result
-
-(
-    echo "(start) $*"
-    set +e
-    if [ -n "$yocto" ]; then
-        echo "$*" | buendia-enter-yocto
-    else
-        eval "$@"
-    fi
-    result=$?
-    echo $result > $RESULT_FILE
-    echo "(end, status $result)"
-) 2>&1 | $tmp/add_timestamps | tee -a $logfile
-
-exit $(cat $RESULT_FILE)
+#!/bin/bash                                                                     
+                                                                                
+set -e; . /usr/share/buendia/utils.sh                                           
+                                                                                
+if [ "$1" = "" -o "$1" = "-h" ]; then                                           
+    echo "Usage: $0 [-y] <command>"                                             
+    echo                                                                        
+    echo "Runs a command and logs its output under /var/log/buendia, exiting"   
+    echo "with the exit status of the command.  Specify -y to run the command"  
+    echo "in Yocto; otherwise it will run in Debian."                           
+    exit 1                                                                      
+fi                                                                              
+                                                                                
+if [ "$1" = "-y" ]; then                                                        
+    yocto=yes                                                                   
+    shift                                                                       
+fi                                                                              
+                                                                                
+# Name the log file after the first word in the command.                        
+logfile=/var/log/buendia/$(basename $(echo "$*" | sed -e 's/ .*//')).log        
+mkdir -p /var/log/buendia                                                       
+                                                                                
+export LOGGER_PID=$$                                                            
+                                                                                
+# Save the exit status of the command so we can exit with the same status.      
+export RESULT_FILE=$tmp/buendia-log.result.$$                                   
+trap 'rm -f $RESULT_FILE' EXIT                                                  
+                                                                                
+(                                                                               
+    echo "(start) $*"                                                           
+    set +e                                                                      
+    if [ -n "$yocto" ]; then                                                    
+        echo "$*" | buendia-enter-yocto                                         
+    else                                                                        
+        eval "$@"                                                               
+    fi                                                                          
+    result=$?                                                                   
+    echo "(end, status $result)"                                                
+    echo $result > $RESULT_FILE                                                 
+) 2>&1 | perl -n -e '                                                           
+    $| = 1;  # unbuffer output                                                  
+    my ($s, $m, $h, $d, $l, $y) = gmtime();                                     
+    printf "%04d-%02d-%02d %02d:%02d:%02d %5d> ",                               
+        $y + 1900, $l + 1, $d, $h, $m, $s, $ENV{"LOGGER_PID"};                  
+    s/^\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d //;                                    
+    print $_;                                                                   
+' | tee -a $logfile                                                             
+                                                                                
+exit $(cat $RESULT_FILE)                                                        
