Fix auto-creation of person and person name.

diff --git a/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql b/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql
--- a/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql
+++ b/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql
@@ -14,6 +14,14 @@ fi
 # Read the settings.
 for f in /usr/share/buendia/site/*; do . $f || true; done
 
+# Ensure that usernames and passwords contain no wonky characters.
+for var in MYSQL_ROOT_PASSWORD; do
+  if ! eval 'echo $'$var | grep -s '^[0-9A-Za-z_-]\+$'; then
+    echo "$var is invalid: only [0-9A-Za-z_-] characters are allowed."
+    exit 1
+  fi
+done
+
 # Check if the root password is already correctly set.
 if mysql -uroot -p$MYSQL_ROOT_PASSWORD </dev/null 2>/dev/null; then
   echo "MySQL root password unchanged."
diff --git a/packages/buendia-tomcat7/data/usr/share/buendia/config.d/tomcat7 b/packages/buendia-tomcat7/data/usr/share/buendia/config.d/tomcat7
--- a/packages/buendia-tomcat7/data/usr/share/buendia/config.d/tomcat7
+++ b/packages/buendia-tomcat7/data/usr/share/buendia/config.d/tomcat7
@@ -2,15 +2,24 @@
 
 SETTINGS=/usr/share/buendia/site/tomcat7
 
-# Create a default settings file if none exists.
+# Generate a random Tomcat admin password if one is not already set.
 if [ ! -f $SETTINGS ]; then
-    cat <<EOF >$SETTINGS
-TOMCAT7_ADMIN_PASSWORD=unconfigured
-EOF
+    password=$(buendia-mkpass)
+    echo "TOMCAT7_ADMIN_PASSWORD=$password" > $SETTINGS
 fi
 
+# Read the settings.
+for f in /usr/share/buendia/site/*; do . $f || true; done
+
+# Ensure that usernames and passwords contain no wonky characters.
+for var in TOMCAT7_ADMIN_PASSWORD; do
+  if ! eval 'echo $'$var | grep -s '^[0-9A-Za-z_-]\+$'; then
+    echo "$var is invalid: only [0-9A-Za-z_-] characters are allowed."
+    exit 1
+  fi
+done
+
 # Apply the settings to the Tomcat configuration.
-source $SETTINGS
 cat <<EOF >/usr/share/buendia/diversions/etc/tomcat7/tomcat-users.xml
 <?xml version='1.0' encoding='utf-8'?>
 <tomcat-users>
