Fix password checking.

diff --git a/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql b/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql
--- a/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql
+++ b/packages/buendia-mysql/data/usr/share/buendia/config.d/mysql
@@ -16,8 +16,8 @@ for f in /usr/share/buendia/site/*; do . $f || true; done
 
 # Ensure that usernames and passwords contain no wonky characters.
 for var in MYSQL_ROOT_PASSWORD; do
-  if ! eval 'echo $'$var | grep -q '^[0-9A-Za-z_-]\+$'; then
-    echo "$var is invalid: only [0-9A-Za-z_-] characters are allowed."
+  if ! eval 'echo $'$var | grep -q '^[0-9A-Za-z._-]\+$'; then
+    echo "$var is invalid: only [0-9A-Za-z._-] characters are allowed."
     exit 1
   fi
 done
diff --git a/packages/buendia-server/data/usr/share/buendia/config.d/server b/packages/buendia-server/data/usr/share/buendia/config.d/server
--- a/packages/buendia-server/data/usr/share/buendia/config.d/server
+++ b/packages/buendia-server/data/usr/share/buendia/config.d/server
@@ -27,8 +27,8 @@ MYSQL="mysql -u$OPENMRS_MYSQL_USER -p$OPENMRS_MYSQL_PASSWORD openmrs"
 
 # Ensure that usernames and passwords contain no wonky characters.
 for var in SERVER_OPENMRS_USER SERVER_OPENMRS_PASSWORD; do
-  if ! eval 'echo $'$var | grep -q '^[0-9A-Za-z_-]\+$'; then
-    echo "$var is invalid: only [0-9A-Za-z_-] characters are allowed."
+  if ! eval 'echo $'$var | grep -q '^[0-9A-Za-z._-]\+$'; then
+    echo "$var is invalid: only [0-9A-Za-z._-] characters are allowed."
     exit 1
   fi
 done
