Refactor config.d/10-networking pt 2, based on PR feedback.
* Rename configure_interface to configure_ip_address
* Ensure ifup/ifdown happen at the same level of the call stack
* Break up configure_base_settings
* Add check_network_settings / commit_network_settings

diff --git a/packages/buendia-networking/data/usr/share/buendia/config.d/10-networking b/packages/buendia-networking/data/usr/share/buendia/config.d/10-networking
--- a/packages/buendia-networking/data/usr/share/buendia/config.d/10-networking
+++ b/packages/buendia-networking/data/usr/share/buendia/config.d/10-networking
@@ -17,13 +17,10 @@ interface_exists () {
     [ -n "$1" ] && ( ip a | grep -q " $1:" )
 }
 
-# Configure an interface in /etc/network/interfaces
-configure_interface () {
+# Configure an interface address in /etc/network/interfaces
+configure_ip_address () {
     iface=$1
     addr=$2
-
-    # Bring down the interface during reconfiguration, but don't fail if we can't.
-    ifdown $iface || true
 
     # If the interface was given a static IP address, then apply it.
     # Otherwise, configure it to use DHCP.
@@ -47,14 +44,21 @@ configure_ethernet () {
         return 0
     fi
 
+    # Adopt NETWORKING_IP_ADDRESS as a default if NETWORKING_ETHERNET_ADDRESS
+    # isn't set
     if [ -z "$NEWORKING_ETHERNET_ADDRESS" ]; then
         NETWORKING_ETHERNET_ADDRESS=$NETWORKING_IP_ADDRESS
         NETWORKING_IP_ADDRESS=""
     fi
 
-    configure_interface "$NETWORKING_ETHERNET_INTERFACE" \
+    # Bring down the interface during reconfiguration, but don't fail if we can't.
+    ifdown $NETWORKING_ETHERNET_INTERFACE || true
+
+    # Configure the IP address for this Interface
+    configure_ip_address "$NETWORKING_ETHERNET_INTERFACE" \
         "$NETWORKING_ETHERNET_ADDRESS" >> /etc/network/interfaces
 
+    # Bring it back up
     ifup $NETWORKING_ETHERNET_INTERFACE
 }
 
@@ -75,7 +79,11 @@ configure_wifi () {
         NETWORKING_IP_ADDRESS=""
     fi
 
-    configure_interface "$NETWORKING_WIFI_INTERFACE" "$NETWORKING_WIFI_ADDRESS" >> /etc/network/interfaces
+    # Bring down the interface during reconfiguration, but don't fail if we can't.
+    ifdown $NETWORKING_WIFI_INTERFACE || true
+
+    # Configure the IP address for this Interface
+    configure_ip_address "$NETWORKING_WIFI_INTERFACE" "$NETWORKING_WIFI_ADDRESS" >> /etc/network/interfaces
 
     # If $NETWORKING_AP is set, enable hostapd and return early.
     if bool $NETWORKING_AP; then
@@ -130,8 +138,22 @@ configure_wifi () {
     ifup $NETWORKING_WIFI_INTERFACE
 }
 
-# Create the tmp_settings file and configure the loopback device
-configure_base_settings () {
+# Check the network settings to see if we need to configure networking.
+check_network_settings () {
+    # Exit early if we have no interfaces to configure. This is potentially
+    # nominal, e.g. when running in the cloud, and is not treated as an error.
+    if ! interface_exists "$NETWORKING_WIFI_INTERFACE" && \
+       ! interface_exists "$NETWORKING_ETHERNET_INTERFACE"; then
+       echo "No known network interfaces available; skipping network configuration."
+       return 0
+    fi
+
+    # Create a file that records the requested settings in a canonical format.
+    # We'll put this in a temporary location for now, and move it over to /run
+    # to indicate that the settings have been applied successfully.
+    tmp_settings=/tmp/buendia-networking.settings.$$
+    run_settings=/run/buendia-networking.settings
+
     # This file persists as a record of successful configuration.  It should
     # exist if and only if the settings it contains were completely and
     # successfully applied.
@@ -145,19 +167,28 @@ configure_base_settings () {
     if [ "$1" != "-f" ]; then
         if [ -e $run_settings ] && diff -q $tmp_settings $run_settings; then
             echo "Networking configuration unchanged."
-            exit 0
+            return 1
         fi
     fi
 
     # In case anything goes wrong, don't leave behind an indicator of success.
     rm -f $run_settings
+}
 
-    # Back up the original interfaces file.
+# Record the fact that the settings that were successfully configured.
+commit_network_settings () {
+    mv $tmp_settings $run_settings
+}
+
+# Back up the original interfaces file if no backup has been made.
+backup_original_interfaces_file () {
     if [ ! -e /etc/network/interfaces.pre-buendia ]; then
         cp /etc/network/interfaces /etc/network/interfaces.pre-buendia
     fi
+}
 
-    # Configure the loopback device
+# Configure the loopback device
+configure_loopback () {
     unindent <<< "
         # Generated by buendia-networking
         auto lo
@@ -205,30 +236,22 @@ configure_services () {
     fi
 }
 
-# Create a file that records the requested settings in a canonical format.
-# We'll put this in a temporary location for now, and move it over to /run
-# to indicate that the settings have been applied successfully.
-tmp_settings=/tmp/buendia-networking.settings.$$
-run_settings=/run/buendia-networking.settings
+# Check to make sure the networking stack needs configuration, and exit early if not.
+check_network_settings || exit 0
 
-if ! interface_exists "$NETWORKING_WIFI_INTERFACE" && \
-   ! interface_exists "$NETWORKING_ETHERNET_INTERFACE"; then
-   echo "No known network interfaces available; skipping network configuration."
-   return 0
-fi
+# Backup the pre-buendia config
+backup_original_interfaces_file
 
-# Set up the $tmp_settings file and configure the loopback interface
-configure_base_settings
-
-# Configure the WiFi and Ethernet interfaces
+# Configure the networking devices
+configure_loopback
 configure_wifi
 configure_ethernet
 
 # Configure DHCP and DNS 
 configure_services
 
-# Record the fact that the settings that were successfully configured.
-mv $tmp_settings $run_settings || true
-
 # Update the /etc/hosts file with mappings for this machine's IP addresses.
 buendia-update-hosts
+
+# Record success
+commit_network_settings
