Don't leave behind network settings in /run unless we know they are good.

diff --git a/packages/buendia-networking/data/usr/share/buendia/config.d/networking b/packages/buendia-networking/data/usr/share/buendia/config.d/networking
--- a/packages/buendia-networking/data/usr/share/buendia/config.d/networking
+++ b/packages/buendia-networking/data/usr/share/buendia/config.d/networking
@@ -10,23 +10,31 @@ if [ -z "$NETWORKING_SSID" ]; then
     exit 1
 fi
 
-# Create a file that records the settings in a canonical format.
+# Create a file that records the requested settings in a canonical format.
 # We'll put this in a temporary location for now, and move it over to /run
 # to indicate that the settings have been applied successfully.
-tmp_last=/tmp/buendia-networking.last.$$
-run_last=/run/buendia-networking.last
-trap 'rm -f $tmp_last' EXIT
-buendia-settings | grep '^NETWORKING_' > $tmp_last
+tmp_settings=/tmp/buendia-networking.settings.$$
+buendia-settings | grep '^NETWORKING_' > $tmp_settings
+trap 'rm -f $tmp_settings' EXIT  # clean up temporary files
 
-# Check the record of the last settings that were applied, so we can avoid
-# bringing the network down if nothing has changed.  Specifying the -f switch
-# forces reconfiguration even when nothing appears to have changed.
+# This file persists as a record of successful configuration.  It should
+# exist if and only if the settings it contains were completely and
+# successfully applied.
+run_settings=/run/buendia-networking.settings
+
+# Compare the desired settings against those that were last successfully
+# applied, allowing us to avoid bringing the network down if nothing has
+# changed.  (Specifying the -f switch forces reconfiguration even when
+# nothing appears to have changed.)
 if [ "$1" != "-f" ]; then
-    if [ -e $run_last ] && diff -q $tmp_last $run_last; then
+    if [ -e $run_settings ] && diff -q $tmp_settings $run_settings; then
         echo "Networking configuration unchanged."
         exit 0
     fi
 fi
+
+# In case anything goes wrong, don't leave behind an indicator of success.
+rm $run_settings
 
 # Apply the settings to the Debian network interface configuration.
 unindent <<< "
@@ -75,10 +83,10 @@ if $(bool $NETWORKING_AP); then
     echo "Becoming an AP, creating wifi network '$NETWORKING_SSID'."
 
     # hostapd runs in Yocto, so this script writes to hostapd.conf directly.
-    cp $tmp_last /etc/buendia-networking
+    cp $tmp_settings /etc/buendia-networking.settings
     buendia-enter-yocto <<< '
         hostapd_conf=/etc/hostapd/hostapd.conf
-        . /debian/etc/buendia-networking
+        . /debian/etc/buendia-networking.settings
 
         cp $hostapd_conf.pre-buendia $hostapd_conf
         echo "ssid=$NETWORKING_SSID" >> $hostapd_conf
@@ -91,7 +99,7 @@ if $(bool $NETWORKING_AP); then
 
 else
     echo "Joining existing wifi network '$NETWORKING_SSID'."
-    cp $tmp_last /etc/buendia-networking
+    cp $tmp_settings /etc/buendia-networking.settings
     buendia-enter-yocto <<< '
         # Stop being an access point now, and do not become one on future boots.
         systemctl stop hostapd
@@ -99,7 +107,7 @@ else
 
         # Connect to an existing wifi network.  This also causes the system
         # to connect again on boot, reusing the same network SSID and password.
-        . /debian/etc/buendia-networking
+        . /debian/etc/buendia-networking.settings
         PATH=/usr/local/bin:/usr/bin:$PATH
         wifi $NETWORKING_SSID:$NETWORKING_PASSWORD
     '
@@ -111,4 +119,4 @@ if $(bool $NETWORKING_DHCP_DNS_SERVER); then
 fi
 
 # Record the fact that the settings that were successfully configured.
-mv $tmp_last $run_last
+mv $tmp_settings $run_settings
