Skip networking configuration if we're not running on a machine with the expected interface name.

diff --git a/packages/buendia-networking/data/usr/share/buendia/config.d/networking b/packages/buendia-networking/data/usr/share/buendia/config.d/networking
--- a/packages/buendia-networking/data/usr/share/buendia/config.d/networking
+++ b/packages/buendia-networking/data/usr/share/buendia/config.d/networking
@@ -18,6 +18,11 @@ else
   MAIN_INTERFACE=$WIFI_INTERFACE
 fi
 
+if ! ( ip a | grep -q " $MAIN_INTERFACE:" ); then
+    echo "Main interface $MAIN_INTERFACE not found. Skipping network configuration."
+    exit 0
+fi
+
 set -e; . /usr/share/buendia/utils.sh
 
 # Update the /etc/hosts file with mappings for this machine's IP addresses.
