Execute Debian startup scripts on startup.

diff --git a/devices/server/usr/local/bin/install-buendia-base b/devices/server/usr/local/bin/install-buendia-base
--- a/devices/server/usr/local/bin/install-buendia-base
+++ b/devices/server/usr/local/bin/install-buendia-base
@@ -20,12 +20,13 @@ if wifi -; ! ping -c 1 -w 1 debian.org; then
   fi
 fi
 
-# Wipe and install Debian under $ROOT using cdebootstrap.
+# Wipe and install Debian under $ROOT using cdebootstrap.  If the installation
+# fails (most likely due to network unavailability), reboot and try again.
 rm -rf $ROOT
-install-debian
+install-debian || reboot
 
 # Install a .bashrc file for root in the Debian chroot.
-cat '<<EOF' >$ROOT/root/.bashrc
+cat <<'EOF' >$ROOT/root/.bashrc
 PATH=/usr/local/bin:$PATH
 PS1='\[\033[33m\]\h(debian)[\!]\$\[\033[0m\] '
 export LS_OPTIONS='--color=auto'
@@ -33,10 +34,10 @@ alias ls='ls $LS_OPTIONS'
 alias ll='ls -l $LS_OPTIONS'
 EOF
 
-# Add custom package repositories.
-cp /etc/buendia-base.sources.list $ROOT/etc/apt/sources.list.d || true
+# Add custom package repositories (no need to quit if this file is missing).
+cp -f /etc/buendia-base.sources.list $ROOT/etc/apt/sources.list.d || true
 
-# Do the rest of the setup operations within Debian.
+# Do the rest of the setup steps below within Debian.
 cat <<EOF | enter-debian
 set -e
 
