Add utils.sh, a place for common shell functions.

diff --git a/packages/tests/check-site-syntax b/packages/tests/check-site-syntax
--- a/packages/tests/check-site-syntax
+++ b/packages/tests/check-site-syntax
@@ -1,13 +1,23 @@
 #!/bin/bash
 
 for file in data/usr/share/buendia/site/*; do
-    if [ -f $file ]; then
+    if [ -e $file ]; then
         if [ -x $file ]; then
             echo "$file should not be executable.  Please chmod a-x all files in site/ before building."
             ls -al $file
             exit 1
         fi
         echo -n "Checking syntax of $file... "
-        bash $file && echo OK
+        (
+            . $file
+            for var in $(grep -o -E '^\w*_USER\b|^\w*_PASSWORD\b' $file); do
+                if ! eval 'echo $'$var | grep -q '^[0-9A-Za-z._-]\+$'; then
+                    echo
+                    echo "$var is invalid: only [0-9A-Za-z._-] characters are allowed."
+                    exit 1
+                fi
+            done
+        ) && echo OK
     fi
 done
+
