Fix root password initialization.

diff --git a/packages/buendia-mysql/root/usr/share/buendia/config.d/mysql b/packages/buendia-mysql/root/usr/share/buendia/config.d/mysql
--- a/packages/buendia-mysql/root/usr/share/buendia/config.d/mysql
+++ b/packages/buendia-mysql/root/usr/share/buendia/config.d/mysql
@@ -14,7 +14,15 @@ fi
 # Read the settings.
 . $SETTINGS
 
-# Create a MySQL initialization file that sets the root password.
+# Check if the root password is already correctly set.
+if mysql -uroot -p$MYSQL_ROOT_PASSWORD </dev/null 2>/dev/null; then
+  echo "MySQL root password unchanged."
+  exit 0
+else
+  echo "Setting MySQL root password..."
+fi
+
+# Create a MySQL init-file that sets the root password.
 umask 066
 cat <<EOF >$INITSQL
 update mysql.user set password=password('$MYSQL_ROOT_PASSWORD') where user='root';
@@ -23,15 +31,26 @@ EOF
 chgrp mysql $INITSQL
 chmod g+r $INITSQL
 
-# Configure MySQL to run the initialization file on startup.
+# Configure MySQL to run the init-file on startup.
 cat <<EOF >$CONF
 [mysqld]
 init_file=$INITSQL
 EOF
 
-# Make MySQL restart and execute the initialization file.
+# Make MySQL restart and execute the init-file.
 service mysql restart
+sleep 1
 
-# Clean up and restart again under normal conditions.
+# Clean up the init-file and restart again under normal conditions.
 rm -f $INITSQL $CONF
 service mysql restart
+sleep 1
+
+# Confirm that the root password was correctly set.
+if mysql -uroot -p$MYSQL_ROOT_PASSWORD </dev/null 2>/dev/null; then
+  echo "MySQL root password successfully changed."
+  exit 0
+else
+  echo "Could not set MySQL root password!"
+  exit 1
+fi
