Fix tools/fetch.

diff --git a/tools/fetch b/tools/fetch
--- a/tools/fetch
+++ b/tools/fetch
@@ -21,13 +21,17 @@ if [ -f $cached ]; then
     echo "Copying cached file to $dest."
     cp $cached $dest
 else
-    echo Fetching $dest...
-    curl -o "$dest" -L "$url" || \
-        echo "Fetch failed." && exit 1
+    echo Fetching $url...
+    if ! curl -o "$dest" -L "$url"; then
+        echo "Fetch failed."
+        exit 1
+    fi
 
     fetched_hash=$($md5 $dest | grep -o '[0-9a-f]\{32\}')
-    [ $fetched_hash == $hash ] || \
-        echo "Fetched file does not have the expected hash!" && exit 1
+    if [ $fetched_hash != $hash ]; then
+        echo "Fetched file does not have the expected hash!"
+        exit 1
+    fi
 
     cp $dest $cached
 fi
