fix openmrs_setup

diff --git a/tools/openmrs_setup b/tools/openmrs_setup
--- a/tools/openmrs_setup
+++ b/tools/openmrs_setup
@@ -21,11 +21,13 @@ if [ "$1" = "-f" ]; then
     force_flag="-f"
     shift
 fi
+site="$1"
+site_sql="$SITE_SQL_DIR/site-$site.sql"
 cd $(dirname $0)
 cd ..  # go to the root of the Buendia repository
 
-if [ "$1" = "-h" ]; then
-    echo "Usage: $0 [-f]"
+if [ "$1" = "-h" -o -z "$site" ]; then
+    echo "Usage: $0 [-f] <site-id>"
     echo
     echo 'Installs the OpenMRS platform, configures it to use MySQL, sets up'
     echo 'the MySQL user openmrs_user with the password "openmrs", and'
@@ -33,6 +35,21 @@ if [ "$1" = "-h" ]; then
     echo 'directory.  By default, this will refuse to overwrite the MySQL'
     echo 'database named "openmrs" if it already exists; specify -f to wipe'
     echo 'and replace the existing database.'
+    echo
+    echo 'You must specify a site ID corresponding to a SQL file in:'
+    echo "    $SITE_SQL_DIR"
+    echo 'For example, use "openmrs_setup dev" to load site-dev.sql.'
+    echo
+    exit 1
+fi
+
+if [ ! -f "$site_sql" ]; then
+    echo "$site_sql not found."
+    echo
+    echo 'You must specify a site ID corresponding to a SQL file in:'
+    echo "    $SITE_SQL_DIR"
+    echo 'For example, use "openmrs_setup dev" to load site-dev.sql.'
+    echo
     exit 1
 fi
 
@@ -60,7 +77,6 @@ if [ ! -f $server_dir/openmrs-$OPENMRS_PLATFORM_VERSION.war ]; then
     echo '  - Accept the default port number'
     echo '  - Accept "no debugging" by default'
     echo '  - Choose MySQL 5.6'
-    echo '  - Choose "no" for preinstalled data'
     echo
     echo -n 'Please make a note of the above.  Ready? '
     read
@@ -110,8 +126,25 @@ profile_manager.profile_dir=$profiles_dir
 EOF
 echo 'Configured OpenMRS to use the MySQL user openmrs_user@localhost.'
 
+# Get the latest database snapshot.
+git submodule update --init db-snapshot
+zip -qj /tmp/init.$$.zip db-snapshot/*
+trap 'rm -f /tmp/init.$$.zip' EXIT
+
+# Load the snapshot into the MySQL database.
+export MYSQL_USER=openmrs_user
+export MYSQL_PASSWORD=openmrs
+echo
+tools/openmrs_load $force_flag openmrs /tmp/init.$$.zip
+
+# Apply the selected site configuration.
+echo
+echo "Loading $site_sql..."
+mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" openmrs < $site_sql
+echo
+
 # Set up the OpenMRS account for Buendia.
 tools/openmrs_account_setup buendia buendia
 
 echo
-echo "Database initialization complete."
+echo "Database initialization complete (site ID: $site)."
