Fix openmrs_load.

diff --git a/tools/openmrs_load b/tools/openmrs_load
--- a/tools/openmrs_load
+++ b/tools/openmrs_load
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 set -e
-if [ $1 == "-f" ]; then
+if [ "$1" == "-f" ]; then
     force=yes
     shift
 fi
@@ -27,6 +27,11 @@ if [ -z "$MYSQL_USER" ]; then
     exit 1
 fi
 
+if [ ! -f "$dumpfile" ]; then
+    echo "$dumpfile: no such file."
+    exit 1
+fi
+
 tmpdir=/tmp/openmrs_load.$$
 tmpzip=/tmp/openmrs_dump.$$.zip
 function cleanup() {
@@ -37,19 +42,21 @@ trap cleanup EXIT
 mysql="mysql -u $MYSQL_USER -p$MYSQL_PASSWORD"
 
 # Create an empty database.
-if $mysql -e '' $db; then
+if $mysql -e '' $db 2>/dev/null; then
     if [ "$force" == yes ]; then
         echo "Wiping existing database $db..."
-        $mysql -s -e 'show tables;' $db | sed -e 's/^/; set session foreign_key_checks=0; drop table /' | $mysql $db
+        $mysql -s -e 'show tables;' $db 2>/dev/null | sed -e 's/^/; set session foreign_key_checks=0; drop table /' | $mysql $db
     else
         echo "Database $db already exists!  To wipe and replace it, use -f."
         exit 1
     fi
-else if $mysql -s -e "create database $db"; then
-    echo 'Created a new empty database.'
 else
-    echo 'Failed to create database $db.'
-    exit 1
+    if $mysql -s -e "create database $db" 2>/dev/null; then
+        echo 'Created a new empty database.'
+    else
+        echo 'Failed to create database $db.'
+        exit 1
+    fi
 fi
 
 # Unpack the zip file in the temporary directory.
