Add buendia-led.

diff --git a/tools/warmup b/tools/warmup
--- a/tools/warmup
+++ b/tools/warmup
@@ -65,10 +65,7 @@ function check_url() {
             echo "No response from server."
         fi
 
-        if [ -e /dev/ttyMFD1 ]; then
-            # Turn off green LED on failure.
-            (stty 115200; echo -e "JFFLG0\r\n") </dev/ttyMFD1 >/dev/ttyMFD1
-        fi
+        buendia-led green off || true  # failure
 
         if [ -z "$retry" ]; then
             false
@@ -93,7 +90,4 @@ echo
 echo "    \o/  Success!  Buendia API at $hostport is up."
 echo
 
-if [ -e /dev/ttyMFD1 ]; then
-    # Turn on green LED on success.
-    (stty 115200; echo -e "JFFLG1\r\n") </dev/ttyMFD1 >/dev/ttyMFD1
-fi
+buendia-led green on || true  # success
